### PR TITLE
Fix vlog.sync()

### LINKED ISSUE #783: Badger crashes on open if last saved head is not pointing to latest value log file
**Way to reproduce:**
1. Run **fill** command for inserting large number of entries(100M) then kill it after some time. Try to run it again.
2. Change **Close** method of **DB** to push head with {0 0 0} value in **flushTask**.

**Reason**
Currently after flushing a Memtable, vlog.sync() is called. sync() tries to sync latest value log file(file with maximum ID). After restart, badger tries to replay all the entries from last saved head. If head is not pointing to latest file, replay will start from here and latest file wont be opened till then. If Memtable is flushed during this time, calling sync() will return error. This will create some assertion failure.

### PR DESCRIPTION
**Pull request by ashish-goswami**
vlog.sync() syncs only latest value log file(vlog.maxFid). There can
be case when vlog.maxFid is not opened and vlog.sync() is called(during
replay when head is not pointing to vlog.maxFid). Hence it will return
error. This causes assertion y.AssertTrue(ft.mt == db.imm[0]) in db.go
to fail, resulting in crash of badger. This commit fixes it by accepting
an argument fid in vlog.sync method. If fid < vlog.maxFid, it returns
without doing anything.

Fixes #783 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/787)

### CODE REVIEW

File: test.sh [hunk 1]
```diff
@@ -23,9 +23,9 @@ rm -R p || true
 echo
 echo "==> Starting tests with value log mmapped..."
 sleep 5
-go test -v --vlog_mmap=true -race ./...
+go test -v --vlog_mmap=true -race -timeout 900s ./...
```
Comment (jarifibrahim) [inline test.sh]: @ashish-goswami why do we need to increase the timeout? Is there a test that doesn't complete in 10 minutes (default timeout) ?

**Comment by jarifibrahim** [comment]
@ashish-goswami This PR would fix https://github.com/dgraph-io/badger/issues/783, isn't it?

File: test.sh (hunk 1 above)
Comment (ashish-goswami) [reply test.sh]: Once my build failed with message `tests ran too long` and hence changed it. I have removed the commit now. It was just for debugging.
