### PR TITLE
Cast results of len to uint32 to fix compilation in i386 arch.

### LINKED ISSUE #953: Compiling for 32 bit
### What version of Go are you using (`go version`)?1.12.5

<pre>
$ go version

</pre>

### What did you see instead?
./../github.com/dgraph-io/badger/table/builder.go:134:27: constant 4294967295 overflows int
../../github.com/dgraph-io/badger/table/builder.go:186:47: constant 4294967295 overflows int
../../github.com/dgraph-io/badger/table/builder.go:204:28: constant 4294967295 overflows int
../../github.com/dgraph-io/badger/table/builder.go:272:17: constant 4294967295 overflows int
../../github.com/dgraph-io/badger/table/builder.go:304:17: constant 4294967295 overflows int

In builder.go everywhere it has math.MaxUint32 I think it should be math.MaxInt32.

I made this change locally and all is OK

### PR DESCRIPTION
**Pull request by martinmr**
GOARCH=386 go build ./ passes with this change and fails without it due
to integer overflow.

Fixes #953

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/961)

### CODE REVIEW

File: table/builder.go [hunk 1]
```diff
@@ -173,7 +173,7 @@ func (b *Builder) shouldFinishBlock(key []byte, value y.ValueStruct) bool {
 		return false
 	}
 
-	y.AssertTrue((len(b.entryOffsets)+1)*4+4+8+4 < math.MaxUint32) // check for below statements
+	y.AssertTrue((uint32(len(b.entryOffsets))+1)*4+4+8+4 < math.MaxUint32) // check for below statements
```
Comment (golangcibot) [inline table/builder.go]: line is 101 characters (from `lll`)

File: table/builder.go [hunk 2]
```diff
@@ -173,7 +173,8 @@ func (b *Builder) shouldFinishBlock(key []byte, value y.ValueStruct) bool {
 		return false
 	}
 
-	y.AssertTrue((len(b.entryOffsets)+1)*4+4+8+4 < math.MaxUint32) // check for below statements
+	// Integer overflow check for statements below.
+	y.AssertTrue((uint32(len(b.entryOffsets))+1)*4+4+8+4 < math.MaxUint32)
```
Comment (golangcibot) [inline table/builder.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)
```suggestion
	y.AssertTrue((uint32(len(b.entryOffsets))+1)*4+4+8+4 < math.MaxUint32)
```
