### PR TITLE
Bug Fix: Truncate of penultimate log files

### LINKED ISSUE #613: Issue truncating vlog after crash
Hello,

We had a server crash and after the crash Badger is having issues truncating vlog files. The error we get is:

`truncate ./Values/002077.vlog: invalid argument`

I've tried a few things to debug. I moved the data to another drive, reformated, used a different filesystem (this is happening on XFS). No luck.

### PR DESCRIPTION
**Pull request by manishrjain**
Value log files minus the most recent log one, were being opened with read-only permissions. If the value head pointer was pointing to them, and one of them had a file system corruption issue, where they missed their bits, it would cause Badger to try to truncate them. Being read-only, this would cause an "invalid argument" to be returned by the Go file.truncate call. This error caused confusion before, but essentially, it was being returned because the files were read-only, and therefore couldn't be truncated (EINVAL).

This PR fixes that by refactoring how value log is opened. It iterates over the log files, and if they need to be replayed, it would open them in RW mode; allowing truncation to happen. Then, it would open them in the mode they can be consumed by Badger.

Fixes #613 .

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/616)

### CODE REVIEW

File: db.go [hunk 1]
```diff
@@ -144,22 +144,26 @@ func replayFunction(out *DB) func(Entry, valuePointer) error {
...
-
-		} else {
+		} else if e.meta&bitTxn > 0 {
 			txnTs := y.ParseTs(nk)
 			if lastCommit == 0 {
 				lastCommit = txnTs
 			}
-			y.AssertTrue(lastCommit == txnTs)
+			if lastCommit != txnTs {
+				// We have found an incomplete txn. Let's discard it.
```
Comment (manishrjain) [inline db.go]: Add a log here.

File: value.go [hunk 2]
```diff
@@ -598,25 +598,26 @@ func (vlog *valueLog) fpath(fid uint32) string {
...
-	var maxFid uint32 // Beware len(files) == 0 case, this starts at 0.
 	for _, file := range files {
 		if !strings.HasSuffix(file.Name(), ".vlog") {
 			continue
 		}
 		fsz := len(file.Name())
 		fid, err := strconv.ParseUint(file.Name()[:fsz-5], 10, 32)
 		if err != nil {
-			return errors.Wrapf(err, "Error while parsing value log id for file: %q", file.Name())
+			return fmt.Errorf("Unable to parse value log id for file %q. Err=%v", file.Name(), err)
```
Comment (manishrjain) [inline value.go]: Switch to errFile

File: value.go [hunk 3]
```diff
@@ -689,18 +662,124 @@ func (vlog *valueLog) createVlogFile(fid uint32) (*logFile, error) {
...
+		if fid < vlog.maxFid {
+			if err := lf.openReadOnly(); err != nil {
+				return err
+			}
+		} else {
+			var flags uint32
+			if vlog.opt.SyncWrites {
+				flags |= y.Sync
+			}
+			if vlog.opt.ReadOnly {
```
Comment (manishrjain) [inline value.go]: Can be switch case with ReadOnly option at the top.

File: value_test.go [hunk 4]
```diff
@@ -397,8 +398,11 @@ func TestValueGC4(t *testing.T) {
 	kv.vlog.rewrite(lf0, tr)
 	kv.vlog.rewrite(lf1, tr)
 
+	// This function is no longer available.
```
Comment (manishrjain) [inline value_test.go]: Remove.

File: value_test.go [hunk 5]
```diff
@@ -397,8 +398,11 @@ func TestValueGC4(t *testing.T) {
...
 	// Replay value log
-	kv.vlog.Replay(valuePointer{Fid: 2}, replayFunction(kv))
+	// kv.vlog.Replay(valuePointer{Fid: 2}, kv.replayFunction())
```
Comment (manishrjain) [inline value_test.go]: Remove line.

File: value_test.go [hunk 6]
```diff
@@ -667,6 +671,56 @@ func createVlog(t *testing.T, entries []*Entry) []byte {
...
+		fpath := vlogFilePath(dir, uint32(i))
+		fi, err := os.Stat(fpath)
+		require.NoError(t, err)
+		require.True(t, fi.Size() > 0, "Empty file at log=%d", i)
+		if i == 0 {
+			err := os.Truncate(fpath, fi.Size()-1)
+			require.NoError(t, err)
+		}
+	}
+	// require.NoError(t, db0.Close())
```
Comment (manishrjain) [inline value_test.go]: Remove line.

File: value_test.go [hunk 7]
```diff
@@ -764,7 +831,8 @@ func BenchmarkReadWrite(b *testing.B) {
 				dir, err := ioutil.TempDir("", "vlog")
 				y.Check(err)
 				defer os.RemoveAll(dir)
-				err = vl.Open(nil, getTestOptions(dir))
+				// TODO: Fix this up.
+				// err = vl.Open(nil, getTestOptions(dir))
```
Comment (manishrjain) [inline value_test.go]: Fix this.
